// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArkBattleCard: typeof import('./components/ark/ArkBattleCard.vue')['default']
    ArkDayCard: typeof import('./components/ark/ArkDayCard.vue')['default']
    ArkEventItem: typeof import('./components/ark/ArkEventItem.vue')['default']
    ArkLevelBadge: typeof import('./components/ark/ArkLevelBadge.vue')['default']
    ArkLogo: typeof import('./components/ark/ArkLogo.vue')['default']
    ArkPlayerAvatar: typeof import('./components/ark/ArkPlayerAvatar.vue')['default']
    ArkTameCard: typeof import('./components/ark/ArkTameCard.vue')['default']
    GameLivesLineChart: typeof import('./components/GameLivesLineChart.vue')['default']
    HeaderBar: typeof import('./components/HeaderBar.vue')['default']
    HeaderBarYt: typeof import('./components/HeaderBarYt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SteamIdEntry: typeof import('./components/SteamIdEntry.vue')['default']
    TtvStatus: typeof import('./components/TtvStatus.vue')['default']
    VodsCalendar: typeof import('./components/VodsCalendar.vue')['default']
  }
}
