// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    GameLivesLineChart: typeof import('./components/GameLivesLineChart.vue')['default']
    HeaderBar: typeof import('./components/HeaderBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SteamIdEntry: typeof import('./components/SteamIdEntry.vue')['default']
    Timeline: typeof import('./components/Timeline.vue')['default']
    TtvStatus: typeof import('./components/TtvStatus.vue')['default']
  }
}
